export type Lang = 'en' | 'cs';

export const strings = {
  en: {
    langToggle: 'CS',
    heroHeadline: 'NICE SCAN, BUTTERCUP.',
    heroSubhead: "Here's 10% off your first online order — because queer pride has no expiration date.",
    heroTagline: 'One little scan, one very happy fan.',
    offerText: '10% off your first online order.\nOne email and it\'s yours.',
    identityPrompt: "Who's coloring?",
    identityGuy: 'Guy',
    identityGirl: 'Girl',
    identityOther: 'Queer',
    namePlaceholder: 'Your name (optional)',
    emailPlaceholder: 'Your email',
    consentText: 'Yes, send me my discount and the occasional filthy email. Unsubscribe anytime.',
    consentPrivacy: 'Privacy',
    formMicrocopy: 'We only send the good stuff. Pinky promise.',
    submitButton: 'Get my 10%',
    submitMicrocopy: 'No regrets. Just discounts.',
    submitting: 'Sending…',
    successTitle: 'Check your inbox, gorgeous.',
    successText: 'Confirm your email and the code\'s all yours. 📩',
    productHeading: "What you're about to color",
    footerBrand: 'DickObraz',
    footerHandle: '@dickobraz.cz',
    errorEmail: 'Please enter a valid email address.',
    errorConsent: 'Please accept the terms to continue.',
    errorGeneric: 'Something went wrong. Please try again.',
  },
  cs: {
    langToggle: 'EN',
    heroHeadline: 'PĚKNÝ SKEN, ZLATÍČKO.',
    heroSubhead: 'Tady je 10 % slevy na první online nákup — protože queer hrdost nemá datum spotřeby.',
    heroTagline: 'Jeden sken a spousta radosti.',
    offerText: '10 % sleva na první online nákup.\nStačí jeden e-mail.',
    identityPrompt: 'Kdo barví?',
    identityGuy: 'Kluk',
    identityGirl: 'Holka',
    identityOther: 'Queer',
    namePlaceholder: 'Tvoje jméno (nepovinné)',
    emailPlaceholder: 'Tvůj e-mail',
    consentText: 'Jo, pošlete mi slevu a občas nějaký ten špinavý e-mail. Kdykoli se odhlásím.',
    consentPrivacy: 'Zásady ochrany',
    formMicrocopy: 'Posíláme jen to dobré. Sliby sliby.',
    submitButton: 'Chci svých 10 %',
    submitMicrocopy: 'Žádné výčitky. Jen slevy.',
    submitting: 'Odesílám…',
    successTitle: 'Koukni do e-mailu, zlatíčko.',
    successText: 'Potvrď e-mail a kód je tvůj. 📩',
    productHeading: 'Co budeš brzy barvit',
    footerBrand: 'DickObraz',
    footerHandle: '@dickobraz.cz',
    errorEmail: 'Zadej platnou e-mailovou adresu.',
    errorConsent: 'Souhlas je potřeba k pokračování.',
    errorGeneric: 'Něco se pokazilo. Zkus to znovu.',
  },
} as const;
